# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addNoiseToDataVector <- function(dataVector, scaleGaussian, rSeed) {
    .Call(`_faust_addNoiseToDataVector`, dataVector, scaleGaussian, rSeed)
}

cppGrowAnnotationForest <- function(rawDataMatrix, dipT, clusterLB, repeatsAllowed, maxSearchDepth, maxClusterNum, verboseForestRun, maxNumberOfGates, randomSearch, numThreadsRequested, useRestrictedValue, restrictedValueMatrix, numGateUB, maxSearchTime, gaussianScale, randomSeed, subSampleThreshold, subSampleSize, subSampleIterations, recordCounts, recordIndices) {
    .Call(`_faust_cppGrowAnnotationForest`, rawDataMatrix, dipT, clusterLB, repeatsAllowed, maxSearchDepth, maxClusterNum, verboseForestRun, maxNumberOfGates, randomSearch, numThreadsRequested, useRestrictedValue, restrictedValueMatrix, numGateUB, maxSearchTime, gaussianScale, randomSeed, subSampleThreshold, subSampleSize, subSampleIterations, recordCounts, recordIndices)
}

doubleDip <- function(x) {
    .Call(`_faust_doubleDip`, x)
}

gateSample <- function(annotationMatrix, selectedChannels, gateNums, scampCellPops) {
    .Call(`_faust_gateSample`, annotationMatrix, selectedChannels, gateNums, scampCellPops)
}

getAnnotationStats <- function(filePaths, requestedLookup, minClusterSize, minProportion, numThreadsToUse) {
    .Call(`_faust_getAnnotationStats`, filePaths, requestedLookup, minClusterSize, minProportion, numThreadsToUse)
}

getCountMatrix <- function(annotationFilePaths, reportingFilePaths, sampleNames, lookupOrder, lookupNames, minClusterSize, minProportion, numThreadsToUse) {
    .Call(`_faust_getCountMatrix`, annotationFilePaths, reportingFilePaths, sampleNames, lookupOrder, lookupNames, minClusterSize, minProportion, numThreadsToUse)
}

getTautStringApprox <- function(dataVec) {
    .Call(`_faust_getTautStringApprox`, dataVec)
}

labelPartition <- function(partitionScores, colNames, colScoreRange) {
    .Call(`_faust_labelPartition`, partitionScores, colNames, colScoreRange)
}

mkSessionAnnMat <- function(expMatFP, newAMFP, cpList) {
    invisible(.Call(`_faust_mkSessionAnnMat`, expMatFP, newAMFP, cpList))
}

singleDip <- function(x) {
    .Call(`_faust_singleDip`, x)
}

subsampleTest <- function(sortedData, subSampleSize, subSampleIterations) {
    .Call(`_faust_subsampleTest`, sortedData, subSampleSize, subSampleIterations)
}

tripleDip <- function(x) {
    .Call(`_faust_tripleDip`, x)
}

tsGates <- function(xVec, modePrior) {
    .Call(`_faust_tsGates`, xVec, modePrior)
}

